image: beevelop/nodejs-python-ruby

job 1:
  stage: build
  script: 
    - pip install xml2rfc wget  
    - gem install kramdown-rfc2629
    - python -c 'import wget; wget.download("https://github.com/martinthomson/i-d-template/archive/master.tar.gz", out="master.tar.gz")'
    - tar xzf master.tar.gz -C lib --strip-components=1
    - make

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
