image: icnteam/internet-drafts:latest

stages:
  - build
  - deploy

internet drafts:
  stage: build
  script: 
    - make
    - make pdf
    - mkdir public
    - cp *.txt *.html *.pdf public
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  image: alpine:latest
  stage: deploy
  script: 
    - cp -f index.html  public
  dependencies:
    - internet drafts
  artifacts:
    paths:
      - public
  only:
    - master