image: icnteam/internet-drafts:latest

stages:
  - build
  - build_doc
  - deploy

internet drafts:
  stage: build
  script: 
    - make
    - make pdf
    - mkdir public
    - cp *.txt *.html public
  artifacts:
    paths:
      - public
  only:
    - master

pdf:
  image:  
  stage: build_doc
  scri

pages:
  image: alpine:latest
  stage: deploy
  script: 
    - cp -f index.html  public
  dependencies:
    - internet drafts
  artifacts:
    paths:
      - public
  only:
    - master