image: martinthomson/i-d-template

stages:
  - build

rfc:
  stage: build
  script: 
    - make
    - mkdir .public
    - cp -r *.txt *.html .public
    - mv .public public
  artifacts:
    paths:
      - public