image: martinthomson/i-d-template

stages:
  - build
  - deploy

internet drafts:
  stage: build
  script: 
    - make
    - mkdir public
    - cp *.txt *.html public
  artifacts:
    paths:
      - public
  only:
    - master
    
pages:
  stage: deploy
  script: 
    - mkdir public
    - cp -f *.txt *.html *.css  public
  artifacts:
    paths:
      - public
  only:
    - gh-pages