image: martinthomson/i-d-template

stages:
  - build
  - deploy

internet drafts:
  stage: build
  script: 
    - make
    - apt-get install -y enscript ps2pdf
    - make pdf
    - mkdir public
    - cp *.txt *.html public
  artifacts:
    paths:
      - public
  only:
    - master
    
pages:
  image: alpine:latest
  stage: deploy
  script: 
    - cp -f index.html  public
  dependencies:
    - internet drafts
  artifacts:
    paths:
      - public
  only:
    - master