name: Build Internet-Drafts from markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: 'checkout'
      uses: actions/checkout@v2
    - name: 'docker hub login'
      uses: azure/docker-login@v1
      with:
          login-server: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'build internet drafts'
      shell: bash
      run: |
        docker run -v $PWD:/workspace icnteam/internet-drafts:latest bash -c "cd /workspace; make; make pdf"
        mdkir -p public; mv *.pdf *.html *.txt public/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./public
