name: Build Internet-Drafts from markdown

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Docker hub login'
      uses: azure/docker-login@v1
      with:
          login-server: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'Build and store container image'
    - uses: actions/checkout@master
    - name: Create Image and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: icnteam/internet-drafts:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        dockerfile: Dockerfile
    - name: 'Build internet drafts'
      shell: bash
      run: |
        docker run -v $PWD:/workspace icnteam/internet-drafts:latest bash -c "cd /workspace; make; make pdf"
        mkdir -p public; cp -f *.pdf *.html *.txt *.png public/
    - name: 'Deploy GH pages'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}

