name: Build Internet Drafts from markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: docker://icnteam/internet-drafts:latest
      with:
        shell: bash
        run: |
          make
          make pdf
        
