name: Build Internet-Drafts from markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: 'checkout'
      uses: actions/checkout@v2
    - name: 'docker hub login'
      uses: azure/docker-login@v1
      with:
          login-server: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'build internet drafts'
      shell: bash
      run: |
        docker run -v $PWD:/workspace icnteam/internet-drafts:latest bash -c "cd /workspace; make; make pdf"
    - name: 'pub to gh-pages'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f *.html *.txt *.pdf; git stash; git fetch
        git checkout gh-pages; rm *.git stash apply; git add *.html *.txt *.pdf
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
