name: Build Internet Drafts from markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
          login-server: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }
      - name: 'build markdown'    
        shell: bash
        run: |
            docker run -v $PWD:/workspace icnteam/internet-drafts:latest bash -c "cd /workspace; make"